// ─────────────────────────────────────────────────────────────────────────────
// MOCK wBTC — Testnet ERC20 token
//
// A mintable ERC20 with 8 decimals mimicking wBTC.
// Anyone can call free_mint() or mint_to() to get test tokens.
// The mock gate calls mint_to() internally to simulate yield coming from
// an external protocol.
// For Testnet purposes for the Hackathon MVP.
// ─────────────────────────────────────────────────────────────────────────────

#[starknet::contract]
pub mod MockWBTC {
    use nova::interfaces::i_mock_wbtc::IMockWBTC;
    use openzeppelin::token::erc20::{ERC20Component, ERC20HooksEmptyImpl};
    use starknet::{ContractAddress, get_caller_address};


    component!(path: ERC20Component, storage: erc20, event: ERC20Event);

    // ERC20 internals
    #[abi(embed_v0)]
    impl ERC20Impl = ERC20Component::ERC20Impl<ContractState>;

    impl ERC20InternalImpl = ERC20Component::InternalImpl<ContractState>;

    // 1 wBTC = 100_000_000 units (8 decimals)
    const DECIMALS: u8 = 8;

    // Authorised minter — set to the mock gate address after deployment
    #[storage]
    struct Storage {
        #[substorage(v0)]
        erc20: ERC20Component::Storage,
    }

    #[event]
    #[derive(Drop, starknet::Event)]
    pub enum Event {
        #[flat]
        ERC20Event: ERC20Component::Event,
    }


    #[constructor]
    fn constructor(ref self: ContractState) {
        self.erc20.initializer("Wrapped Bitcoin", "wBTC");
    }

    #[abi(embed_v0)]
    impl FakeWBTCImpl of IMockWBTC<ContractState> {
        // ── free_mint
        // ─────────────────────────────────────────────────────
        // For minting caller tokens
        fn free_mint(ref self: ContractState, amount: u256) {
            let caller = get_caller_address();
            self.erc20.mint(caller, amount);
        }

        // ── mint_to
        // ───────────────────────────────────────────────────────
        // Used to simulate yield being generated by an external protocol.
        fn mint_to(ref self: ContractState, recipient: ContractAddress, amount: u256) {
            self.erc20.mint(recipient, amount);
        }


        fn decimals(self: @ContractState) -> u8 {
            DECIMALS
        }
    }
}
